name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPASS }}" | docker login -u "imgurmeet" --password-stdin
        docker image build -t imgurmeet/hello_from_github:latest .
        docker push imgurmeet/hello_from_github:latest

